swagger: '2.0'
info:
  version: '1.0'
  title: "TacoLento"
  description: TacoLento is an API that allows it's users to create and manage exams and tasks.
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /users:
    x-summary: Users
    post:
      description: Insert new user
      responses:
        201:
          description: User created
        400: 
          description: Invalid input
        409: 
          description: An user whit this email was already found.
          
  /user/{id}:
    x-summary: Update, search or delete a user
    get:
      description: Find user info
      parameters:
         - name: id
           in: path
           description: exam ID
           required: true
           type: integer
      responses:
       302: 
         description: User found
       400: 
         description: Invalid input
       404:
         description: User not found
    put:
      description: Update user info
      parameters:
         - name: id
           in: path
           description: exam ID
           required: true
           type: integer
      responses:
       202: 
         description: User updated
       400: 
         description: Invalid input
       404: 
         description: User not found
    delete:
      description: delete user
      parameters:
         - name: id
           in: path
           description: exam ID
           required: true
           type: integer
      responses:
       202: 
         description: User deleted
       404: 
         description: User not found
  
  /tasks:
    x-summary: Tasks Collection
    get:
      description: List All Tasks
#      parameters:
#          in: query
#          name: MC
#          schema:
#            type: string
#            enum: [MC,CC, OpenAnswer]
#          required: false
      responses:
        200:
          description: Successful response
        400: 
          description: Invalid input
    post:
      description: New Task
      responses:
        201:
          description: Task created 
        400:
          description: Invalid input
          
  /task/{id}:
    x-summary: Update, search or delete a task
    get:
      description: Find task
      parameters:
        - name: id
          in: path
          description: exam ID
          required: true
          type: integer
      responses:
        201: 
          description: Task found
        400: 
          description: Invalid input
        404:
          description: Task not found
    post:
      description: Update task
      parameters:
        - name: id
          in: path
          description: exam ID
          required: true
          type: integer
      responses:
        201: 
          description: Task updated
        400: 
          description: Invalid input
        404:
          description: Task not found
    delete:
      description: Delete task
      parameters:
        - name: id
          in: path
          description: exam ID
          required: true
          type: integer
      responses:
        201: 
          description: Task deleted
        404:
          description: Task not found
          

          
  /exams:
    x-summary: Exams Collection
    get:
      summary: List All Exams
      responses:
        200:
          description: Successful response
        400: 
          description: Invalid input
    post:
      description: New exams
      summary: Create a New Exam
      responses:
        201:
          description: Exams created
        400:
          description: Invalid input

  /exams/{id}:
    x-summary: Update, search or delete exam 
    get:
      description: Find exam
      parameters:
        - name: id
          in: path
          description: exam ID
          required: true
          type: integer
      responses:
        201: 
          description: Exam find
        400: 
          description: Invalid input
    post:
      description: Update Exam
      parameters:
        - name: id
          in: path
          description: exam ID
          required: true
          type: integer
      responses:
         201: 
           description: Exam updated
         400: 
           description: Invalid input
    delete:
      description: Delete Exam
      parameters:
        - name: id
          in: path
          description: exam ID
          required: true
          type: integer
      responses:
        201: 
          description: Exam deleted
        400: 
          description: Invalid input