swagger: '2.0'
info:
  version: '1.0'
  title: "TacoLento_project"
  description: TacoLento_project Api
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /users:
    x-summary: Users Collection
    post:
      description: Insert new user
      summary: Create a New User
      responses:
        201:
          description: User Created
        400: 
          description: Invalid Input
        404: 
          description: An user whit this email was not found.
          
#/users/{id}:
#  x-summary: Update, search or delete user 
#  get:
#    description: Find user info
#      parameters:
#        - name: id
#          in: path
#          description: exam ID
#          required: true
#          type:integer
#    responses:
#      201: 
#        description: User info
#      400: 
#        description: Invalid input
#  put:
#    description: Update user info
#      parameters:
#        - name: id
#          in: path
#          description: exam ID
#          required: true
#          type:integer
#    responses:
#      201: 
#        description: User update
#      400: 
#        description: Invalid input
#  delete:
#    description: delete user
#      parameters:
#        - name: id
#          in: path
#          description: exam ID
#          required: true
#          type:integer
#    responses:
#      201: 
#        description: User deleted
#      400: 
#        description: Invalid input
  
  /tasks:
    x-summary: Tasks Collection
    get:
      summary: List All Tasks
#      parameters:
#          in: query
#          name: MC
#          schema:
#            type: string
#            enum: [MC,CC, OpenAnswer]
#          required: false
      responses:
        200:
          description: Successful Response
        400: 
          description: Invalid Input
    post:
      description: New Task
      summary: Create a New Task
      responses:
        201:
          description: Task created 
        400:
          description: Invalid Input
          
#  /tasks/{id}:
#    x-summary: Update, search or delete task
#    get:
#      description: Find task
#      parameters:
#        - name: id
#          in: path
#          description: exam ID
#          required: true
#          type:integer
#      responses:
#        201: 
#          description: Task Find
#        400: 
#          description: Invalid input
#    put:
#      description: Update task
#      parameters:
#        - name: id
#          in: path
#          description: exam ID
#          required: true
#          type:integer
#      responses:
#        201: 
#          description: task updated
#        400: 
#          description: Invalid input
#    delete:
#      description: delete task
#      parameters:
#        - name: id
#          in: path
#          description: exam ID
#          required: true
#          type:integer
#      responses:
#        201: 
#          description: Task deleted
#        400: 
#          description: Invalid input
          

          
  /exams:
    x-summary: Exams Collection
    get:
      summary: List All exams
      responses:
        200:
          description: Successful Response
        400: 
          description: Invalid Input
    post:
      description: New exams
      summary: Create a New Exams
      responses:
        201:
          description: Exams created
        400:
          description: Invalid Input

#  /exams/{id}:
#    x-summary: Update, search or delete exam 
#    get:
#      description: Find exam
#      parameters:
#        - name: id
#          in: path
#          description: exam ID
#          required: true
#          type:integer
#      responses:
#        201: 
#          description: Exam find
#        400: 
#          description: Invalid input
#    put:
#      description: Update Exam
#      parameters:
#        - name: id
#          in: path
#          description: exam ID
#          required: true
#          type:integer
#      responses:
#         201: 
#           description: Exam updated
#         400: 
#           description: Invalid input
#    delete:
#      description: delete Exam
#      parameters:
#        - name: id
#          in: path
#          description: exam ID
#          required: true
#          type:integer
#      responses:
#        201: 
#          description: Exam deleted
#        400: 
#          description: Invalid input