swagger: '2.0'
info:
  version: '1.0'
  title: "TacoLento_project"
  description: TacoLento_project Api
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /users:
    x-summary: Path che si occupa degli users
    post:
      description: insert new user
      summary: Create a New Question
      responses:
        201:
          description: User insert
        400: 
          description: Invalid Input
        404: 
          description: An user whit the same email already exists
          
  #/user/{id}:
  #  x-summary: Update, search or delete user 
  #  parameters:
  #    - name: id
  #      in: path
  #      description: User ID
  #      required: true
  #      schema:
  #        type: integer
  #  get:
  #    description: Find user info
  #    responses:
  #      201: 
  #        description: User info
  #      400: 
  #        description: Invalid input
  #  put:
  #    description: Update user info
  #    responses:
  #      201: 
  #        description: User update
  #      400: 
  #        description: Invalid input
  #  delete:
  #    description: delete user
  #    responses:
  #      201: 
  #        description: User deleted
  #      400: 
  #        description: Invalid input
  
  /tasks:
    x-summary: Questions Collection
    get:
      summary: List All Questions
#      parameters:
#        - in: query
#          name: MC
#          schema:
#            type: string
#            enum: [MC, OpenAnswer]
#          required: false
      responses:
        200:
          description: Successful Response
        400: 
          description: Invalid Input
    post:
      description: New Question
      summary: Create a New Question
      responses:
        201:
          description: Task insert 
        400:
          description: Invalid Input
          
#  /task/{id}:
#    x-summary: Update, search or delete task
#    parameters:
#      - name: id
#        in: path
#        description: User ID
#        required: true
#        schema:
#          type: integer
#    get:
#      description: Find task
#      responses:
#        201: 
#          description: Task Find
#        400: 
#          description: Invalid input
#    put:
#      description: Update task
#      responses:
#        201: 
#          description: task updated
#        400: 
#          description: Invalid input
#    delete:
#      description: delete task
#      responses:
#        201: 
#          description: Task deleted
#        400: 
#          description: Invalid input
          

          
  /exams:
    x-summary: Exams Collection
    get:
      summary: List All exams
      responses:
        200:
          description: Successful Response
        400: 
          description: Invalid Input
    post:
      description: New exams
      summary: Create a New Exams
      responses:
        201:
          description: Exams insert 
        400:
          description: Invalid Input

#  /exam/{id}:
#    x-summary: Update, search or delete exam 
#    parameters:
#      - name: id
#        in: path
#        description: exam ID
#        required: true
#        schema:
#          type: integer
#    get:
#      description: Find exam
#      responses:
#        201: 
#          description: Exam find
#        400: 
#          description: Invalid input
#    put:
#      description: Update Exam
#     responses:
#        201: 
#          description: Exam updated
#        400: 
#          description: Invalid input
#    delete:
#      description: delete Exam
#      responses:
#        201: 
#          description: Exam deleted
#        400: 
#          description: Invalid input